### ISSUE TITLE
Add accessibility support

### ISSUE THREAD

**Issue by booc0mtaco** [booc0mtaco/start#9]
## Handle Navigation

With this site, there will be a grid of buttons to navigate to a new page. We expect by default that tabbing thru the results should highlight each option, and describe the option at the cursor, and tell the user what that option is (for screen reader support). Further, we should allow for keyboard navigation to work. 

- Arrow keys will move between each option until the edges of the grid are hit. Once the edge is hit, no wrapping will occur
- However, when tabbing, it should wrap back around to the initial option on the page (depending on the layout, the first button, or the first page control (for edit, etc.))

### TODO

- [x] enable support for tabbing thru buttons
- [ ] enable support for using arrow keys to navigate thru buttons with wrap prevention (down/right are forward, up/left are back)
- [x] enable visual indicators for focused button
- [x] enable handling for activation keys on focused button (enter/space keys, or VO-activation)
- [x] enable appropriate roles for buttons

## User Notification

We should provide a notice to the user for buttons, by adding a target for AX messaging. When a button is activated, it should tell the user what is being opened while (or before) opening it.

### TODO

- [ ] support screen readers with hidden container set to `aria-live="polite"` (e.g., `role="alert"`)

## Initial State

When the page loads, it should automatically target the initial start point. In this case, We should make sure that when the user is able to press any control, it will land on the top-left button to start.

### TODO

- [ ] upon load, make sure that the first tab or arrow starts on the first button
- [ ] reloads should preserve this

**Comment by booc0mtaco** [comment]
# Supporting key navigation and element focusing in vue

## when the app loads, we need to select the first button

- here, we can make use of the [`created`](https://vuejs.org/v2/api/#created) hook to know that the component is loaded, but it won't be ready to use just yet. The elements are added on screen via the [`mounted`](https://vuejs.org/v2/api/#mounted) hook, which guarantees the HTML has been drawn on screen.
- The app should grab focus upon load, then take control of keyboard presses from there on

*Remember not to use arrow functions for hooks, as The VueJS people know what `this` is, and use it intentionally. If we need some async thing, we can use `.bind(this)`as needed.

## Support for keyboard navigation

### Approach one

Tabbing currently works on the elements, but the arrow keys have no specific behavior. We have access to a global event listener on `keydown` to detect keyboard presses, and a hook for incrementing and decrementing the item to focus on.

We need to modify `start-button` to handle `focus` based on an app index in such a way that tabbing and arrows do not get out of sync. We can capture all those key strokes in JS and allow the tab fallback. 

* **Tab / ArrowRight / ArrowDown** will increment the position of the selected button and focus it
* **Shift+Tab / ArrowLeft / ArrowUp** will decrement the position of the selected button and focus it
* pressing any of the button keys mapped to each button should first focus, then activate the button
* **Spacebar/Enter** on any button should activate the currently selected button

We can use [Vue directives](https://vuejs.org/v2/guide/syntax.html#Directives) potentially to handle this. if the app implements `v-on:keypress`, we can route all keyboard events for the buttons. [More on v-on directives](https://vuejs.org/v2/guide/events.html)

We should also consider using [modifiers](https://vuejs.org/v2/guide/syntax.html#Modifiers) to prevent default behavior.

## Highlighting selected option

We can use [`v-bind:class`](https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax) to handle setting a focus state along with `:focus` and `:active`
